version: "3"

services:
  db:
    container_name: shopper_db
    image: mysql:8.0
    platform: linux/x86_64
    restart: always
    volumes:
      - ./database:/var/lib/mysql
    ports:
      - 33060:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
