version: '3'
services:
  db:
    image: mysql:8.0
    container_name: db
    volumes:
      - ./database:/var/lib/mysql
    ports:
      - 33060:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password